AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'example-lambda-sns

  Example CloudFormation template to subscribe a lambda to an SNS Topic.

  '
Resources:
  ExampleTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: example-sns-topic
      TopicName:
        Fn::Sub: example-sns-topic
      Subscription:
      - Protocol: lambda
        Endpoint:
          Fn::GetAtt:
          - ExampleFunction
          - Arn
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dsandor-examples/386ea3ede3a16631d373404e211dcbfa
      Handler: index.handler
      Runtime: nodejs8.10
  ExampleFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: ExampleFunction
      Principal: sns.amazonaws.com
  ExampleTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
      - Ref: ExampleTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sns:Publish
          Resource:
            Ref: ExampleTopic
          Principal:
            AWS: '*'
          Condition:
            ArnLike:
              AWS:SourceArn:
                Fn::Sub: arn:aws:*:*:${AWS::AccountId}:*
